
0. clear environment, package load and set directory
```{r}
rm(list = ls())


##carga paquetes

PAQUETES <- c("dplyr","tidyverse","ggplot2","here","arrow","lubridate","readxl","randomForest","doParallel","caret")

for (el in PAQUETES){
  if (!require(el, character.only = TRUE)) {
    install.packages(el, repos = "https://cloud.r-project.org")
    require(el, character.only = TRUE)
  }
}

rm(PAQUETES, el)

path<-here()
setwd(path)

```

load dataframes
```{r}
setwd(path)

selected_features <- read_excel("~/GitHub/household_energy_consumption/data/data_dictionary.xlsx",sheet=1)%>% 
  filter(selected=="y")%>% 
  pull(field_name)

house_static_data <- read_parquet("https://intro-datascience.s3.us-east-2.amazonaws.com/SC-data/static_house_info.parquet") %>% 
  select(bldg_id,selected_features) %>% 
  select(where(~length(unique(.)) > 1)) 

house_static_data %>%
  mutate(across(where(is.character),as.factor)) %>% 
  # mutate(across(where(is.factor), as.numeric)) %>% 
  mutate(in.cooling_setpoint=as.numeric(substr(in.cooling_setpoint,1,2))) %>% #convert to number
  mutate(in.cooling_setpoint_offset_magnitude=as.numeric(substr(in.cooling_setpoint_offset_magnitude,1,1))) %>% #convert to number
  mutate(in.cooling_setpoint_offset_period = factor(str_extract(in.cooling_setpoint_offset_period, "^[^-+]*"))) %>%  #reomve the ofset magnitude as it is in another column
  mutate(county_id=house_static_data$in.county)->encoded_house_data #I need the county id in code for the join

temperature <-read_csv("~/GitHub/household_energy_consumption/data/temperature.csv") %>% 
  rename(time=date_time)


```

Load a sample of the Energy consumption
```{r}
data <-read_csv("C:/Users/franc/OneDrive/MADS/IST687/final_project/electricity_consumption.csv") %>%
  sample_frac(0.05) %>% #read a sample
  left_join(encoded_house_data,by="bldg_id") %>% 
  left_join(temperature,by=c("county_id","time"))#join with encoded data
  
data %>% 
  select(-bldg_id,-county_id) %>% #remove the id and the county in code
  mutate(day = day(time)) %>% 
  mutate(day_of_week = factor(wday(time, label = TRUE))) %>% 
  mutate(hour=factor(hour(time))) %>% 
  filter(!is.na(temperature)) %>%  #drop the counties where I do not have the temperature
  select(-time) -> data
  
number_of_categories <- sapply(data, function(x) if(is.factor(x)) nlevels(x) else NA)
data.frame(colnames(data),number_of_categories)

```


Run a quick model to get the feature importance on the sample
```{r}

# registerDoParallel(cores = 4)

# Train the model
rf_model <- randomForest(total_electricity ~ ., data=data, ntree=20, mtry=2, nodesize=20,do.trace=1)
end_time <- Sys.time()

# Check out the feature importance
feature_importance <- importance(rf_model)
```



Get the features
```{r}

feature_importance %>% 
  data.frame() %>% 
  arrange(desc(IncNodePurity)) %>% 
  mutate(importance_perc=IncNodePurity/sum(IncNodePurity)*100) %>% 
  filter(importance_perc>.95) -> selected_importance #select those with an importance above 2%

selected_importance %>% pull(importance_perc) %>% sum()

selected_importance_names <- selected_importance %>% rownames()

saveRDS(selected_importance_names,"~/GitHub/household_energy_consumption/selected_importance_names.RDS")

selected_importance <- selected_importance %>%
  mutate(names = factor(selected_importance_names, 
                        levels = selected_importance_names[order(importance_perc, decreasing = TRUE)]))

# Now plot with ggplot2
plot<- ggplot(selected_importance, aes(x = names, y = importance_perc)) +
  geom_col() +
  coord_flip() +  # This will flip the coordinates to make the bars horizontal
  theme_classic() +
  labs(y = "Importance Percentage", x = "Features") + 
  geom_col(fill = "deepskyblue4")

ggsave("~/GitHub/household_energy_consumption/plots/feature_importance_1.png", plot, width = 10, height = 8, dpi = 300)

```

plot the feature importance









